from . import ba_synchronize
from . import res_company
from . import res_partner
from . import res_users
from . import product_template
from . import pos_order
from . import sale_order
from . import stock_warehouse
#from . import uom_category
from . import additional_cost
from . import purchase_line_tax
from . import purchase_order
from . import sale_line_tax
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import stock_location
from . import account_move
from . import ir_sequence
from . import product_pricelist
from . import hr_department
from . import hr_employee
from . import change_prices
from . import pos_config
from . import params_serie_point_sale_warehouse
from . import params_log_comercial
from . import imported_pricelist
from . import barcodes_product
from . import displacement_level
from . import sale_delivery_available_ba
from . import sale_delivery_ba
from . import postal_code
from . import postal_code_sat
from . import colonies_sat
from . import res_city_sat
#from . import latitude_length_by_cp
